name: financefeeder
language: python
variables:
  - name: TRADES_TOPIC
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: trades
    required: true
  - name: FINHUB_ENDPOINT
    inputType: FreeText
    description: ''
    defaultValue: wss://ws.finnhub.io
    required: false
  - name: FINHUB_TOKEN
    inputType: FreeText
    description: ''
    defaultValue: cn22fv1r01qmg1p4cp9gcn22fv1r01qmg1p4cpa0
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
