name: financefeeder
language: python
variables:
  - name: TRADES_TOPIC
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: trades
    required: true
  - name: FINHUB_ENDPOINT
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: FINHUB_TOKEN
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
